load("@prelude//toolchains:demo.bzl", "system_demo_toolchains")

system_demo_toolchains()

load(":verilator.bzl", "system_verilator_toolchain", "verilator_simulator_toolchain")
load(":gtkwave.bzl", "system_gtkwave_toolchain")
system_verilator_toolchain(name = "verilator")
verilator_simulator_toolchain(name = "simulator", visibility = ["PUBLIC"]) # use system verilator to simulate
system_gtkwave_toolchain(name = "waveform_visualizer", visibility = ["PUBLIC"])