load("//rules:sv.bzl", "sv_module", "sv_module_test")

sv_module(
    name = "adder",
    srcs = ["adder.sv"],
    top = "adder",
    deps = [
        "root//hardware/types:types",
    ]
)

sv_module_test(
    name = "tb_basic_functionality",
    srcs = ["tb_basic_functionality.sv"],
    top = "tb",
    deps = [":adder"]
)

test_suite(
    name = "all_tests",
    tests = [
        ":tb_basic_functionality"
    ]
)