load("//rules:sv.bzl", "sv_module", "sv_module_test")

sv_module(
    name = "switchbox",
    srcs = ["switchbox.sv"],
    top = "switchbox",
    deps = [
        "root//hardware/types:types",
    ],
    visibility = ["root//hardware/cgra:cgra"]
)

# sv_module_test(
#     name = "tb_basic_functionality",
#     srcs = ["tb_basic_functionality.sv"],
#     top = "tb",
#     deps = [":switchbox"]
# )

test_suite(
    name = "all_tests",
    tests = [
        ":tb_basic_functionality"
    ]
)